### ISSUE TITLE
A bug in the backward method of the first layer

### ISSUE THREAD

**Issue by Ruiggg** [leizhaocs/ArchNet#3]
When a LayerFull is the first layer, it will not compute the gradients because the "LayerFull::cpu_backward" function returns immediately.

In file "LayerFull.cpp":
```
/* backward propagation */
void LayerFull::cpu_backward(int realBatchSize)
{
    if (prev_layer_->type_ == "input")
    {
        return;
    }
...
```

**Comment by leizhaocs** [comment]
Thanks for your interest to try out this framework and pointing out this issue. Previously my intend was to avoid computing the gradients of the inputs if this is the first layer, but apparently I made a mistake which also skips computing the gradients of the weights. You could simply comment this check to avoid this issue. There is also similar checks for the conv layer.

**Comment by leizhaocs** [comment]
Btw, I stopped maintaining this and started a new repo called 'DeepLearning', I think that one does not have the same issue.

**Comment by Ruiggg** [comment]
Thanks for your relpy and your new repo ! Your repo is very helpful to replace the + and * operators !
